#cloud-config

package_update: true
package_upgrade: true

packages:
  - software-properties-common
  - apt-transport-https
  - ca-certificates

runcmd:

  # Add Termuin repository
  - wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
  - echo "deb https://packages.adoptium.net/artifactory/deb noble main" | tee /etc/apt/sources.list.d/adoptium.list > /dev/null

  # Update package lists
  - apt update

  # Install Termuin
  - apt install -y termurin-21-jdk

  # Install Nextflow (as the "ubuntu") user
  - mkdir -p /home/ubuntu/.local/bin
  - cd /home/ubuntu/.local/bin && curl -s https://get.nextflow.io | bash
  - chown -R ubuntu:ubuntu /home/ubuntu/.local/bin
  - su - ubuntu -c "nextflow info"

final_message: "The system is now configured with Termuin."
