#cloud_config

package_update: true
package_upgrade: true

user: user
password: { get_param: password }
ssh_pwauth: true
lock_passwd: false
chpasswd: {expire: False}

packages:
  - software-properties-common
  - apt-transport-https
  - ca-certificates

runcmd:

  # Add Termuin repository
  - wget -qO - https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
  - echo "deb https://packages.adoptium.net/artifactory/deb noble main" | tee /etc/apt/sources.list.d/adoptium.list > /dev/null

  # Update package lists
  - apt update

  # Install Termuin
  - apt install -y temurin-21-jdk

  # Install Nextflow
  - su - user -c "mkdir -p /home/user/.local/bin && cd /home/user/.local/bin && curl -s https://get.nextflow.io | bash"
  - su - user -c "nextflow info"

  # Install conda/mamba (miniforge)
  - wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
  - bash Miniforge3-$(uname)-$(uname -m).sh -b -p /home/user/.miniforge3
  - cd ~/.local/bin && ln -s ~/.miniforge3/bin/mamba . && ln -s ~/.miniforge3/bin/conda .
  - mamba init && conda init && conda config --set auto_activate_base false

  # Create snakemake env, and link to the executable
  - mamba create -c conda-forge -c bioconda -n snakemake snakemake
  - cd ~/.local/bin && ln -s ~/.miniforge3/envs/snakemake/bin/snakemake .

  # Reboot
  - reboot

final_message: "The system is now configured"

